In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Data processing

In [2]:
movie = pd.read_csv(r"D:\Coding\Data Science\Datasets\tmdb_5000_movies.csv")
credit = pd.read_csv(r"D:\Coding\Data Science\Datasets\tmdb5000_credit.csv")

In [3]:
movie.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movie.shape

(4803, 20)

In [6]:
credit.shape

(4803, 4)

In [7]:
movie = movie.merge(credit,on='title')

In [8]:
movie.shape

(4809, 23)

In [9]:
movie.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [11]:
#Important columns
#genres,id,keywords,title,overview,cast,crew

In [12]:
movie[['id','movie_id']]

          id  movie_id
0      19995     19995
1        285       285
2     206647    206647
3      49026     49026
4      49529     49529
...      ...       ...
4804    9367      9367
4805   72766     72766
4806  231617    231617
4807  126186    126186
4808   25975     25975

[4809 rows x 2 columns]

In [13]:
movie = movie[['id','title','overview','genres','keywords','cast','crew']]

In [14]:
movie.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
movie.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [16]:
movie.dropna(inplace=True)

In [17]:
movie.duplicated().sum()

np.int64(0)

In [18]:
movie.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [19]:
# We need to convert genres in this form
# ['Action','Adventure','Fantasy','Science Fiction']

In [20]:
# This module is used to convert string list to actual list
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [21]:
def convert(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [22]:
movie['genres'] = movie['genres'].apply(convert)

In [23]:
movie.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
movie.iloc[0].keywords

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [25]:
ast.literal_eval(movie.iloc[0].keywords)

[{'id': 1463, 'name': 'culture clash'},
 {'id': 2964, 'name': 'future'},
 {'id': 3386, 'name': 'space war'},
 {'id': 3388, 'name': 'space colony'},
 {'id': 3679, 'name': 'society'},
 {'id': 3801, 'name': 'space travel'},
 {'id': 9685, 'name': 'futuristic'},
 {'id': 9840, 'name': 'romance'},
 {'id': 9882, 'name': 'space'},
 {'id': 9951, 'name': 'alien'},
 {'id': 10148, 'name': 'tribe'},
 {'id': 10158, 'name': 'alien planet'},
 {'id': 10987, 'name': 'cgi'},
 {'id': 11399, 'name': 'marine'},
 {'id': 13065, 'name': 'soldier'},
 {'id': 14643, 'name': 'battle'},
 {'id': 14720, 'name': 'love affair'},
 {'id': 165431, 'name': 'anti war'},
 {'id': 193554, 'name': 'power relations'},
 {'id': 206690, 'name': 'mind and soul'},
 {'id': 209714, 'name': '3d'}]

In [26]:
movie['keywords'] = movie['keywords'].apply(convert)

In [27]:
movie.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [28]:
movie['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [29]:
# In cast data we need only top 3 actor names

In [30]:
def convert3(obj):
    l = []
    count = 0
    for i in ast.literal_eval(obj):
        if count != 3:
            l.append(i['name'])
            count += 1
        else:
            break
    return l

In [31]:
movie['cast'] = movie['cast'].apply(convert3)

In [32]:
movie.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
movie['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [34]:
def fetchDirector(obj):
    l = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l

In [35]:
movie['crew'] = movie['crew'].apply(fetchDirector)

In [36]:
movie.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [37]:
movie['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [38]:
movie['overview'] = movie['overview'].apply(lambda x:x.split())

In [39]:
movie.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [40]:
# We nned to remove spaces between names
# If we put space our ml model get confused to recommandate
# eg. If I want sam mendes movies but sometimes ml model recommandates sam worthington movies because of sam name

In [41]:
movie['genres'] = movie['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movie['genres']

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [42]:
movie['keywords'] = movie['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movie['keywords']

0       [cultureclash, future, spacewar, spacecolony, ...
1       [ocean, drugabuse, exoticisland, eastindiatrad...
2       [spy, basedonnovel, secretagent, sequel, mi6, ...
3       [dccomics, crimefighter, terrorist, secretiden...
4       [basedonnovel, mars, medallion, spacetravel, p...
                              ...
4804    [unitedstates–mexicobarrier, legs, arms, paper...
4805                                                   []
4806    [date, loveatfirstsight, narration, investigat...
4807                                                   []
4808             [obsession, camcorder, crush, dreamgirl]
Name: keywords, Length: 4806, dtype: object

In [43]:
movie['cast'] = movie['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movie['cast']

0        [SamWorthington, ZoeSaldana, SigourneyWeaver]
1           [JohnnyDepp, OrlandoBloom, KeiraKnightley]
2            [DanielCraig, ChristophWaltz, LéaSeydoux]
3            [ChristianBale, MichaelCaine, GaryOldman]
4          [TaylorKitsch, LynnCollins, SamanthaMorton]
                             ...
4804    [CarlosGallardo, JaimedeHoyos, PeterMarquardt]
4805         [EdwardBurns, KerryBishé, MarshaDietlein]
4806           [EricMabius, KristinBooth, CrystalLowe]
4807            [DanielHenney, ElizaCoupe, BillPaxton]
4808    [DrewBarrymore, BrianHerzlinger, CoreyFeldman]
Name: cast, Length: 4806, dtype: object

In [44]:
movie['crew'] = movie['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movie['crew']

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...
4804     [RobertRodriguez]
4805         [EdwardBurns]
4806          [ScottSmith]
4807          [DanielHsia]
4808     [BrianHerzlinger]
Name: crew, Length: 4806, dtype: object

In [45]:
movie.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [46]:
movie['tags'] = movie['genres'] + movie['keywords'] + movie['cast'] + movie['crew']

In [47]:
movie.head()

,id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[Action, Adventure, ScienceFiction, basedonnov..."

In [48]:
df = movie[['id','title','tags']]
df.head()

,id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."

In [49]:
df['tags'] = df['tags'].apply(lambda x:" ".join(x))

C:\Users\SANSKAR\AppData\Local\Temp\ipykernel_17388\4267108141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x:" ".join(x))

In [50]:
df['tags'] = df['tags'].apply(lambda x:x.lower())

C:\Users\SANSKAR\AppData\Local\Temp\ipykernel_17388\841579467.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(lambda x:x.lower())

In [51]:
df.head()

,id,title,tags
0,19995,Avatar,action adventure fantasy sciencefiction cultur...
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,206647,Spectre,action adventure crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...
4,49529,John Carter,action adventure sciencefiction basedonnovel m...

In [52]:
df['tags'][0]

'action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

### Vectorization

In [53]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
vec = cv.fit_transform(df['tags']).toarray()

In [54]:
vec.shape

(4806, 5000)

In [55]:
cv.get_feature_names_out()

array(['15thcentury', '16thcentury', '17thcentury', ..., 'zooeydeschanel',
       'zookeeper', 'zoëkravitz'], dtype=object)

In [56]:
# We need to assume that love,loving,loved words are same
# To do this we need below liberary

In [57]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [58]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [59]:
ps.stem("loving"), ps.stem('loved'), ps.stem('love')

('love', 'love', 'love')

In [60]:
df['tags'] = df['tags'].apply(stem)

C:\Users\SANSKAR\AppData\Local\Temp\ipykernel_17388\866399325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['tags'].apply(stem)

In [61]:
# We need to find diatance (angle) between two movies
# We find the cosine angle between two movies
# If angle is low similarity betwwen two movies is high
# dist -> 1/similarity
# To find this we need below liberary

In [62]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vec)

In [63]:
similarity

array([[1.        , 0.12309149, 0.11605177, ..., 0.06085806, 0.        ,
        0.        ],
       [0.12309149, 1.        , 0.12856487, ..., 0.        , 0.        ,
        0.        ],
       [0.11605177, 0.12856487, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.06085806, 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [64]:
similarity.shape

(4806, 4806)

### Main function to recommand movie

In [65]:
# enumerate creares tuple of index and value
list(enumerate(similarity[0]))

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.12309149097933272)),
 (2, np.float64(0.1160517706371319)),
 (3, np.float64(0.03774256780481986)),
 (4, np.float64(0.27216552697590873)),
 (5, np.float64(0.12598815766974242)),
 (6, np.float64(0.0)),
 (7, np.float64(0.19245008972987526)),
 (8, np.float64(0.10286889997472795)),
 (9, np.float64(0.16012815380508716)),
 (10, np.float64(0.1987615979999813)),
 (11, np.float64(0.11111111111111113)),
 (12, np.float64(0.12598815766974242)),
 (13, np.float64(0.09622504486493763)),
 (14, np.float64(0.18670401120373464)),
 (15, np.float64(0.09335200560186732)),
 (16, np.float64(0.140028008402801)),
 (17, np.float64(0.24077170617153845)),
 (18, np.float64(0.17407765595569785)),
 (19, np.float64(0.17660431427533915)),
 (20, np.float64(0.140028008402801)),
 (21, np.float64(0.11111111111111113)),
 (22, np.float64(0.10675210253672476)),
 (23, np.float64(0.10675210253672476)),
 (24, np.float64(0.09335200560186732)),
 (25, np.float64(0.12909944487358055)),
 (26, np.float64(0.1814436846506058)),
 (27, np.float64(0.14907119849998599)),
 (28, np.float64(0.16051447078102563)),
 (29, np.float64(0.09938079899999065)),
 (30, np.float64(0.140028008402801)),
 (31, np.float64(0.18670401120373464)),
 (32, np.float64(0.1987615979999813)),
 (33, np.float64(0.15430334996209194)),
 (34, np.float64(0.0)),
 (35, np.float64(0.14433756729740643)),
 (36, np.float64(0.21350420507344953)),
 (37, np.float64(0.14907119849998599)),
 (38, np.float64(0.16012815380508716)),
 (39, np.float64(0.15430334996209194)),
 (40, np.float64(0.048112522432468816)),
 (41, np.float64(0.2405626121623441)),
 (42, np.float64(0.0)),
 (43, np.float64(0.12909944487358055)),
 (44, np.float64(0.05802588531856595)),
 (45, np.float64(0.11111111111111113)),
 (46, np.float64(0.1814436846506058)),
 (47, np.float64(0.3849001794597506)),
 (48, np.float64(0.13608276348795434)),
 (49, np.float64(0.1160517706371319)),
 (50, np.float64(0.2321035412742638)),
 (51, np.float64(0.2057377999494559)),
 (52, np.float64(0.18670401120373464)),
 (53, np.float64(0.08606629658238704)),
 (54, np.float64(0.055555555555555566)),
 (55, np.float64(0.16412198797244362)),
 (56, np.float64(0.17407765595569785)),
 (57, np.float64(0.0)),
 (58, np.float64(0.06415002990995841)),
 (59, np.float64(0.16012815380508716)),
 (60, np.float64(0.0)),
 (61, np.float64(0.3333333333333334)),
 (62, np.float64(0.12171612389003693)),
 (63, np.float64(0.140028008402801)),
 (64, np.float64(0.049690399499995326)),
 (65, np.float64(0.03774256780481986)),
 (66, np.float64(0.051434449987363975)),
 (67, np.float64(0.17407765595569785)),
 (68, np.float64(0.14433756729740643)),
 (69, np.float64(0.08830215713766958)),
 (70, np.float64(0.16012815380508716)),
 (71, np.float64(0.21821789023599236)),
 (72, np.float64(0.19245008972987526)),
 (73, np.float64(0.04536092116265145)),
 (74, np.float64(0.2057377999494559)),
 (75, np.float64(0.12171612389003693)),
 (76, np.float64(0.12309149097933272)),
 (77, np.float64(0.04415107856883479)),
 (78, np.float64(0.08606629658238704)),
 (79, np.float64(0.15430334996209194)),
 (80, np.float64(0.09938079899999065)),
 (81, np.float64(0.25717224993681986)),
 (82, np.float64(0.12038585308576921)),
 (83, np.float64(0.3142696805273545)),
 (84, np.float64(0.22222222222222227)),
 (85, np.float64(0.22680460581325726)),
 (86, np.float64(0.17407765595569785)),
 (87, np.float64(0.1160517706371319)),
 (88, np.float64(0.140028008402801)),
 (89, np.float64(0.049690399499995326)),
 (90, np.float64(0.10286889997472795)),
 (91, np.float64(0.19245008972987523)),
 (92, np.float64(0.12038585308576921)),
 (93, np.float64(0.08606629658238704)),
 (94, np.float64(0.25717224993681986)),
 (95, np.float64(0.1301200097264711)),
 (96, np.float64(0.140028008402801)),
 (97, np.float64(0.18257418583505539)),
 (98, np.float64(0.11785113019775793)),
 (99, np.float64(0.04667600280093366)),
 (100, np.float64(0.09938079899999065)),
 (101, np.float64(0.15430334996209194)),
 (102, np.float64(0.22222222222222227)),
 (103, np.float64(0.12309149097933272)),
 (104, np.float64(0.07856742013183862)),
 (105, np.float64(0.1160517706371319)),
 (106, np.float64(0.06700252101728081)),
 (107, np.float64(0.140028008402801)),
 (108, np.float64(0.2333800140046683)),
 (109, np.float64(0.11111111111111113)),
 (110, np.float64(0.04303314829119352)),
 (111, np.float64(0.2057377999494559)),
 (112, np.float64(0.13608276348795437)),
 (113, np.float64(0.08025723539051281)),
 (114, np.float64(0.08206099398622181)),
 (115, np.float64(0.08830215713766958)),
 (116, np.float64(0.09622504486493763)),
 (117, np.float64(0.0907218423253029)),
 (118, np.float64(0.040128617695256406)),
 (119, np.float64(0.06913011298202835)),
 (120, np.float64(0.0)),
 (121, np.float64(0.17407765595569785)),
 (122, np.float64(0.14433756729740643)),
 (123, np.float64(0.12022261795565765)),
 (124, np.float64(0.09335200560186732)),
 (125, np.float64(0.13608276348795434)),
 (126, np.float64(0.2057377999494559)),
 (127, np.float64(0.1814436846506058)),
 (128, np.float64(0.0)),
 (129, np.float64(0.1814436846506058)),
 (130, np.float64(0.060858061945018464)),
 (131, np.float64(0.2041241452319315)),
 (132, np.float64(0.16666666666666669)),
 (133, np.float64(0.049690399499995326)),
 (134, np.float64(0.10286889997472795)),
 (135, np.float64(0.0)),
 (136, np.float64(0.048112522432468816)),
 (137, np.float64(0.0)),
 (138, np.float64(0.14907119849998599)),
 (139, np.float64(0.06163335513613657)),
 (140, np.float64(0.05802588531856595)),
 (141, np.float64(0.09622504486493763)),
 (142, np.float64(0.051434449987363975)),
 (143, np.float64(0.10675210253672476)),
 (144, np.float64(0.03928371006591931)),
 (145, np.float64(0.04415107856883479)),
 (146, np.float64(0.06804138174397717)),
 (147, np.float64(0.12171612389003693)),
 (148, np.float64(0.12830005981991682)),
 (149, np.float64(0.15713484026367724)),
 (150, np.float64(0.16798421022632323)),
 (151, np.float64(0.13608276348795437)),
 (152, np.float64(0.08606629658238704)),
 (153, np.float64(0.10675210253672476)),
 (154, np.float64(0.05802588531856595)),
 (155, np.float64(0.0)),
 (156, np.float64(0.09759000729485331)),
 (157, np.float64(0.17407765595569785)),
 (158, np.float64(0.17213259316477408)),
 (159, np.float64(0.09622504486493763)),
 (160, np.float64(0.17213259316477408)),
 (161, np.float64(0.049690399499995326)),
 (162, np.float64(0.06804138174397717)),
 (163, np.float64(0.09622504486493763)),
 (164, np.float64(0.12171612389003693)),
 (165, np.float64(0.07027283689263066)),
 (166, np.float64(0.17660431427533915)),
 (167, np.float64(0.12830005981991682)),
 (168, np.float64(0.24845199749997662)),
 (169, np.float64(0.17213259316477408)),
 (170, np.float64(0.1160517706371319)),
 (171, np.float64(0.07273929674533079)),
 (172, np.float64(0.2057377999494559)),
 (173, np.float64(0.060858061945018464)),
 (174, np.float64(0.13608276348795437)),
 (175, np.float64(0.10675210253672476)),
 (176, np.float64(0.040128617695256406)),
 (177, np.float64(0.0)),
 (178, np.float64(0.05337605126836238)),
 (179, np.float64(0.12830005981991682)),
 (180, np.float64(0.03513641844631533)),
 (181, np.float64(0.03774256780481986)),
 (182, np.float64(0.21350420507344953)),
 (183, np.float64(0.1382602259640567)),
 (184, np.float64(0.22222222222222227)),
 (185, np.float64(0.10286889997472795)),
 (186, np.float64(0.07027283689263066)),
 (187, np.float64(0.2057377999494559)),
 (188, np.float64(0.04199605255658081)),
 (189, np.float64(0.12830005981991682)),
 (190, np.float64(0.1543033499620919)),
 (191, np.float64(0.08206099398622181)),
 (192, np.float64(0.0)),
 (193, np.float64(0.23570226039551587)),
 (194, np.float64(0.0)),
 (195, np.float64(0.1160517706371319)),
 (196, np.float64(0.08025723539051281)),
 (197, np.float64(0.0907218423253029)),
 (198, np.float64(0.10286889997472795)),
 (199, np.float64(0.12309149097933272)),
 (200, np.float64(0.08399210511316162)),
 (201, np.float64(0.0)),
 (202, np.float64(0.055555555555555566)),
 (203, np.float64(0.16012815380508716)),
 (204, np.float64(0.040128617695256406)),
 (205, np.float64(0.12830005981991682)),
 (206, np.float64(0.25717224993681986)),
 (207, np.float64(0.1814436846506058)),
 (208, np.float64(0.16666666666666669)),
 (209, np.float64(0.060858061945018464)),
 (210, np.float64(0.09622504486493763)),
 (211, np.float64(0.055555555555555566)),
 (212, np.float64(0.12038585308576921)),
 (213, np.float64(0.07273929674533079)),
 (214, np.float64(0.0)),
 (215, np.float64(0.10369516947304253)),
 (216, np.float64(0.10675210253672476)),
 (217, np.float64(0.09938079899999065)),
 (218, np.float64(0.06415002990995841)),
 (219, np.float64(0.12171612389003693)),
 (220, np.float64(0.16012815380508716)),
 (221, np.float64(0.048112522432468816)),
 (222, np.float64(0.12171612389003693)),
 (223, np.float64(0.12171612389003693)),
 (224, np.float64(0.16666666666666669)),
 (225, np.float64(0.09938079899999065)),
 (226, np.float64(0.055555555555555566)),
 (227, np.float64(0.04536092116265145)),
 (228, np.float64(0.22222222222222227)),
 (229, np.float64(0.16012815380508716)),
 (230, np.float64(0.14433756729740643)),
 (231, np.float64(0.0)),
 (232, np.float64(0.18670401120373464)),
 (233, np.float64(0.15430334996209194)),
 (234, np.float64(0.08399210511316162)),
 (235, np.float64(0.10286889997472795)),
 (236, np.float64(0.051434449987363975)),
 (237, np.float64(0.12171612389003693)),
 (238, np.float64(0.19641855032959654)),
 (239, np.float64(0.11111111111111113)),
 (240, np.float64(0.08025723539051281)),
 (241, np.float64(0.17407765595569785)),
 (242, np.float64(0.14433756729740643)),
 (243, np.float64(0.12598815766974242)),
 (244, np.float64(0.11111111111111113)),
 (245, np.float64(0.08206099398622181)),
 (246, np.float64(0.04199605255658081)),
 (247, np.float64(0.0)),
 (248, np.float64(0.041030496993110906)),
 (249, np.float64(0.15430334996209194)),
 (250, np.float64(0.0)),
 (251, np.float64(0.06804138174397717)),
 (252, np.float64(0.04303314829119352)),
 (253, np.float64(0.1160517706371319)),
 (254, np.float64(0.0907218423253029)),
 (255, np.float64(0.0)),
 (256, np.float64(0.10675210253672476)),
 (257, np.float64(0.12830005981991682)),
 (258, np.float64(0.055555555555555566)),
 (259, np.float64(0.11111111111111113)),
 (260, np.float64(0.27216552697590873)),
 (261, np.float64(0.03513641844631533)),
 (262, np.float64(0.11785113019775793)),
 (263, np.float64(0.11111111111111113)),
 (264, np.float64(0.0)),
 (265, np.float64(0.055555555555555566)),
 (266, np.float64(0.1814436846506058)),
 (267, np.float64(0.10286889997472795)),
 (268, np.float64(0.04667600280093366)),
 (269, np.float64(0.049690399499995326)),
 (270, np.float64(0.13245323570650436)),
 (271, np.float64(0.13608276348795437)),
 (272, np.float64(0.06804138174397717)),
 (273, np.float64(0.040128617695256406)),
 (274, np.float64(0.08399210511316162)),
 (275, np.float64(0.13608276348795437)),
 (276, np.float64(0.08830215713766958)),
 (277, np.float64(0.09938079899999065)),
 (278, np.float64(0.21516574145596762)),
 (279, np.float64(0.140028008402801)),
 (280, np.float64(0.0)),
 (281, np.float64(0.03928371006591931)),
 (282, np.float64(0.09938079899999065)),
 (283, np.float64(0.0)),
 (284, np.float64(0.051434449987363975)),
 (285, np.float64(0.055555555555555566)),
 (286, np.float64(0.03513641844631533)),
 (287, np.float64(0.03928371006591931)),
 (288, np.float64(0.0)),
 (289, np.float64(0.10675210253672476)),
 (290, np.float64(0.09938079899999065)),
 (291, np.float64(0.11111111111111113)),
 (292, np.float64(0.16012815380508716)),
 (293, np.float64(0.060858061945018464)),
 (294, np.float64(0.17407765595569785)),
 (295, np.float64(0.16012815380508716)),
 (296, np.float64(0.06600983619844494)),
 (297, np.float64(0.04667600280093366)),
 (298, np.float64(0.0)),
 (299, np.float64(0.08206099398622181)),
 (300, np.float64(0.18670401120373464)),
 (301, np.float64(0.10675210253672476)),
 (302, np.float64(0.14547859349066158)),
 (303, np.float64(0.055555555555555566)),
 (304, np.float64(0.18257418583505539)),
 (305, np.float64(0.19641855032959654)),
 (306, np.float64(0.1160517706371319)),
 (307, np.float64(0.16666666666666669)),
 (308, np.float64(0.12830005981991682)),
 (309, np.float64(0.13608276348795434)),
 (310, np.float64(0.08025723539051281)),
 (311, np.float64(0.15430334996209194)),
 (312, np.float64(0.12830005981991682)),
 (313, np.float64(0.09622504486493763)),
 (314, np.float64(0.0)),
 (315, np.float64(0.19245008972987523)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.12171612389003693)),
 (320, np.float64(0.060858061945018464)),
 (321, np.float64(0.0)),
 (322, np.float64(0.2592592592592593)),
 (323, np.float64(0.08606629658238704)),
 (324, np.float64(0.060858061945018464)),
 (325, np.float64(0.06804138174397717)),
 (326, np.float64(0.09938079899999065)),
 (327, np.float64(0.04536092116265145)),
 (328, np.float64(0.0)),
 (329, np.float64(0.12038585308576921)),
 (330, np.float64(0.12038585308576921)),
 (331, np.float64(0.11111111111111113)),
 (332, np.float64(0.15430334996209194)),
 (333, np.float64(0.04536092116265145)),
 (334, np.float64(0.13245323570650436)),
 (335, np.float64(0.09335200560186732)),
 (336, np.float64(0.11111111111111113)),
 (337, np.float64(0.055555555555555566)),
 (338, np.float64(0.0)),
 (339, np.float64(0.08830215713766958)),
 (340, np.float64(0.12171612389003693)),
 (341, np.float64(0.10675210253672476)),
 (342, np.float64(0.1814436846506058)),
 (343, np.float64(0.0)),
 (344, np.float64(0.07856742013183862)),
 (345, np.float64(0.06415002990995841)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.09622504486493763)),
 (349, np.float64(0.09335200560186732)),
 (350, np.float64(0.10675210253672476)),
 (351, np.float64(0.0)),
 (352, np.float64(0.051434449987363975)),
 (353, np.float64(0.051434449987363975)),
 (354, np.float64(0.0)),
 (355, np.float64(0.036369648372665396)),
 (356, np.float64(0.09622504486493763)),
 (357, np.float64(0.0)),
 (358, np.float64(0.11111111111111113)),
 (359, np.float64(0.11111111111111113)),
 (360, np.float64(0.0)),
 (361, np.float64(0.049690399499995326)),
 (362, np.float64(0.17407765595569785)),
 (363, np.float64(0.11785113019775793)),
 (364, np.float64(0.049690399499995326)),
 (365, np.float64(0.04415107856883479)),
 (366, np.float64(0.11111111111111113)),
 (367, np.float64(0.0)),
 (368, np.float64(0.18257418583505539)),
 (369, np.float64(0.14433756729740643)),
 (370, np.float64(0.08606629658238704)),
 (371, np.float64(0.2321035412742638)),
 (372, np.float64(0.05802588531856595)),
 (373, np.float64(0.15430334996209194)),
 (374, np.float64(0.051434449987363975)),
 (375, np.float64(0.1160517706371319)),
 (376, np.float64(0.12171612389003693)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.17407765595569785)),
 (380, np.float64(0.04303314829119352)),
 (381, np.float64(0.15713484026367724)),
 (382, np.float64(0.0)),
 (383, np.float64(0.08830215713766958)),
 (384, np.float64(0.05337605126836238)),
 (385, np.float64(0.0)),
 (386, np.float64(0.03703703703703704)),
 (387, np.float64(0.04303314829119352)),
 (388, np.float64(0.0)),
 (389, np.float64(0.16666666666666669)),
 (390, np.float64(0.04199605255658081)),
 (391, np.float64(0.09622504486493763)),
 (392, np.float64(0.06415002990995841)),
 (393, np.float64(0.0)),
 (394, np.float64(0.05337605126836238)),
 (395, np.float64(0.048112522432468816)),
 (396, np.float64(0.036369648372665396)),
 (397, np.float64(0.06415002990995841)),
 (398, np.float64(0.0)),
 (399, np.float64(0.048112522432468816)),
 (400, np.float64(0.16666666666666669)),
 (401, np.float64(0.0)),
 (402, np.float64(0.09938079899999065)),
 (403, np.float64(0.140028008402801)),
 (404, np.float64(0.05802588531856595)),
 (405, np.float64(0.049690399499995326)),
 (406, np.float64(0.0)),
 (407, np.float64(0.048112522432468816)),
 (408, np.float64(0.05337605126836238)),
 (409, np.float64(0.0)),
 (410, np.float64(0.13245323570650436)),
 (411, np.float64(0.12171612389003693)),
 (412, np.float64(0.19245008972987523)),
 (413, np.float64(0.15430334996209194)),
 (414, np.float64(0.06804138174397717)),
 (415, np.float64(0.10910894511799618)),
 (416, np.float64(0.08606629658238704)),
 (417, np.float64(0.049690399499995326)),
 (418, np.float64(0.060858061945018464)),
 (419, np.float64(0.13608276348795437)),
 (420, np.float64(0.14433756729740643)),
 (421, np.float64(0.0)),
 (422, np.float64(0.1160517706371319)),
 (423, np.float64(0.048112522432468816)),
 (424, np.float64(0.08206099398622181)),
 (425, np.float64(0.07698003589195011)),
 (426, np.float64(0.14907119849998599)),
 (427, np.float64(0.0)),
 (428, np.float64(0.08606629658238704)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.041030496993110906)),
 (432, np.float64(0.09622504486493763)),
 (433, np.float64(0.05337605126836238)),
 (434, np.float64(0.0)),
 (435, np.float64(0.060858061945018464)),
 (436, np.float64(0.0)),
 (437, np.float64(0.049690399499995326)),
 (438, np.float64(0.060858061945018464)),
 (439, np.float64(0.0)),
 (440, np.float64(0.05802588531856595)),
 (441, np.float64(0.055555555555555566)),
 (442, np.float64(0.07548513560963972)),
 (443, np.float64(0.1160517706371319)),
 (444, np.float64(0.0)),
 (445, np.float64(0.051434449987363975)),
 (446, np.float64(0.03703703703703704)),
 (447, np.float64(0.048112522432468816)),
 (448, np.float64(0.0)),
 (449, np.float64(0.10675210253672476)),
 (450, np.float64(0.055555555555555566)),
 (451, np.float64(0.04303314829119352)),
 (452, np.float64(0.06804138174397717)),
 (453, np.float64(0.051434449987363975)),
 (454, np.float64(0.07548513560963972)),
 (455, np.float64(0.036369648372665396)),
 (456, np.float64(0.049690399499995326)),
 (457, np.float64(0.2041241452319315)),
 (458, np.float64(0.12830005981991682)),
 (459, np.float64(0.048112522432468816)),
 (460, np.float64(0.05802588531856595)),
 (461, np.float64(0.13608276348795434)),
 (462, np.float64(0.0)),
 (463, np.float64(0.07273929674533079)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.2721655269759087)),
 (467, np.float64(0.19245008972987523)),
 (468, np.float64(0.05337605126836238)),
 (469, np.float64(0.09938079899999065)),
 (470, np.float64(0.10675210253672476)),
 (471, np.float64(0.12171612389003693)),
 (472, np.float64(0.17407765595569785)),
 (473, np.float64(0.09622504486493763)),
 (474, np.float64(0.0)),
 (475, np.float64(0.09622504486493763)),
 (476, np.float64(0.12830005981991682)),
 (477, np.float64(0.0)),
 (478, np.float64(0.07698003589195011)),
 (479, np.float64(0.14547859349066158)),
 (480, np.float64(0.10286889997472795)),
 (481, np.float64(0.0)),
 (482, np.float64(0.05802588531856595)),
 (483, np.float64(0.16012815380508716)),
 (484, np.float64(0.05337605126836238)),
 (485, np.float64(0.10286889997472795)),
 (486, np.float64(0.18257418583505539)),
 (487, np.float64(0.16666666666666669)),
 (488, np.float64(0.09938079899999065)),
 (489, np.float64(0.0)),
 (490, np.float64(0.24343224778007386)),
 (491, np.float64(0.16412198797244362)),
 (492, np.float64(0.11111111111111113)),
 (493, np.float64(0.049690399499995326)),
 (494, np.float64(0.0)),
 (495, np.float64(0.2321035412742638)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.07273929674533079)),
 (499, np.float64(0.0)),
 (500, np.float64(0.05337605126836238)),
 (501, np.float64(0.16412198797244362)),
 (502, np.float64(0.11111111111111113)),
 (503, np.float64(0.140028008402801)),
 (504, np.float64(0.0)),
 (505, np.float64(0.17407765595569785)),
 (506, np.float64(0.05337605126836238)),
 (507, np.float64(0.22680460581325726)),
 (508, np.float64(0.14433756729740643)),
 (509, np.float64(0.0)),
 (510, np.float64(0.12909944487358055)),
 (511, np.float64(0.16666666666666669)),
 (512, np.float64(0.055555555555555566)),
 (513, np.float64(0.11111111111111113)),
 (514, np.float64(0.10286889997472795)),
 (515, np.float64(0.05802588531856595)),
 (516, np.float64(0.03928371006591931)),
 (517, np.float64(0.0)),

In [66]:
# We need to sort diatances in reverse order without loosing its index
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, np.float64(1.0000000000000002)),
 (47, np.float64(0.3849001794597506)),
 (2374, np.float64(0.34426518632954817)),
 (61, np.float64(0.3333333333333334)),
 (83, np.float64(0.3142696805273545)),
 (2405, np.float64(0.30123203803835463)),
 (3407, np.float64(0.29095718698132317)),
 (1192, np.float64(0.29012942659282975)),
 (1934, np.float64(0.29012942659282975)),
 (4121, np.float64(0.28867513459481287)),
 (4, np.float64(0.27216552697590873)),
 (260, np.float64(0.27216552697590873)),
 (1827, np.float64(0.27216552697590873)),
 (466, np.float64(0.2721655269759087)),
 (1288, np.float64(0.2721655269759087)),
 (2494, np.float64(0.2721655269759087)),
 (3210, np.float64(0.2721655269759087)),
 (2329, np.float64(0.26688025634181195)),
 (1202, np.float64(0.2649064714130087)),
 (322, np.float64(0.2592592592592593)),
 (786, np.float64(0.2581988897471611)),
 (1325, np.float64(0.2581988897471611)),
 (2359, np.float64(0.2581988897471611)),
 (2756, np.float64(0.2581988897471611)),
 (3997, np.float64(0.2581988897471611)),
 (4490, np.float64(0.2581988897471611)),
 (81, np.float64(0.25717224993681986)),
 (94, np.float64(0.25717224993681986)),
 (206, np.float64(0.25717224993681986)),
 (2071, np.float64(0.25660011963983365)),
 (168, np.float64(0.24845199749997662)),
 (661, np.float64(0.24845199749997662)),
 (490, np.float64(0.24343224778007386)),
 (942, np.float64(0.24343224778007386)),
 (2446, np.float64(0.24343224778007386)),
 (17, np.float64(0.24077170617153845)),
 (838, np.float64(0.24077170617153842)),
 (41, np.float64(0.2405626121623441)),
 (193, np.float64(0.23570226039551587)),
 (1483, np.float64(0.23570226039551587)),
 (1669, np.float64(0.23570226039551587)),
 (2476, np.float64(0.23570226039551587)),
 (2709, np.float64(0.23570226039551587)),
 (4046, np.float64(0.23570226039551587)),
 (4190, np.float64(0.23570226039551587)),
 (108, np.float64(0.2333800140046683)),
 (539, np.float64(0.2333800140046683)),
 (1392, np.float64(0.2333800140046683)),
 (50, np.float64(0.2321035412742638)),
 (371, np.float64(0.2321035412742638)),
 (495, np.float64(0.2321035412742638)),
 (1214, np.float64(0.2321035412742638)),
 (1613, np.float64(0.2321035412742638)),
 (1986, np.float64(0.2321035412742638)),
 (3496, np.float64(0.2321035412742638)),
 (85, np.float64(0.22680460581325726)),
 (507, np.float64(0.22680460581325726)),
 (931, np.float64(0.22680460581325726)),
 (84, np.float64(0.22222222222222227)),
 (102, np.float64(0.22222222222222227)),
 (184, np.float64(0.22222222222222227)),
 (228, np.float64(0.22222222222222227)),
 (859, np.float64(0.22222222222222227)),
 (1045, np.float64(0.22222222222222227)),
 (1087, np.float64(0.22222222222222227)),
 (2682, np.float64(0.22222222222222227)),
 (4405, np.float64(0.22222222222222227)),
 (71, np.float64(0.21821789023599236)),
 (2594, np.float64(0.21821789023599236)),
 (3728, np.float64(0.21821789023599236)),
 (3860, np.float64(0.21821789023599236)),
 (4254, np.float64(0.21821789023599236)),
 (278, np.float64(0.21516574145596762)),
 (36, np.float64(0.21350420507344953)),
 (182, np.float64(0.21350420507344953)),
 (577, np.float64(0.21350420507344953)),
 (777, np.float64(0.21350420507344953)),
 (1193, np.float64(0.21350420507344953)),
 (2200, np.float64(0.21350420507344953)),
 (4336, np.float64(0.21350420507344953)),
 (582, np.float64(0.20998026278290405)),
 (3160, np.float64(0.20998026278290405)),
 (51, np.float64(0.2057377999494559)),
 (74, np.float64(0.2057377999494559)),
 (111, np.float64(0.2057377999494559)),
 (126, np.float64(0.2057377999494559)),
 (172, np.float64(0.2057377999494559)),
 (187, np.float64(0.2057377999494559)),
 (1654, np.float64(0.2057377999494559)),
 (2165, np.float64(0.2057377999494559)),
 (131, np.float64(0.2041241452319315)),
 (457, np.float64(0.2041241452319315)),
 (715, np.float64(0.2041241452319315)),
 (1571, np.float64(0.2041241452319315)),
 (1671, np.float64(0.2041241452319315)),
 (1682, np.float64(0.2041241452319315)),
 (2657, np.float64(0.2041241452319315)),
 (3233, np.float64(0.2041241452319315)),
 (3734, np.float64(0.2041241452319315)),
 (10, np.float64(0.1987615979999813)),
 (32, np.float64(0.1987615979999813)),
 (939, np.float64(0.1987615979999813)),
 (972, np.float64(0.1987615979999813)),
 (238, np.float64(0.19641855032959654)),
 (305, np.float64(0.19641855032959654)),
 (7, np.float64(0.19245008972987526)),
 (72, np.float64(0.19245008972987526)),
 (754, np.float64(0.19245008972987526)),
 (1231, np.float64(0.19245008972987526)),
 (1766, np.float64(0.19245008972987526)),
 (2311, np.float64(0.19245008972987526)),
 (2786, np.float64(0.19245008972987526)),
 (2792, np.float64(0.19245008972987526)),
 (3091, np.float64(0.19245008972987526)),
 (3156, np.float64(0.19245008972987526)),
 (3363, np.float64(0.19245008972987526)),
 (3487, np.float64(0.19245008972987526)),
 (3781, np.float64(0.19245008972987526)),
 (4146, np.float64(0.19245008972987526)),
 (4213, np.float64(0.19245008972987526)),
 (4320, np.float64(0.19245008972987526)),
 (4560, np.float64(0.19245008972987526)),
 (4657, np.float64(0.19245008972987526)),
 (4737, np.float64(0.19245008972987526)),
 (91, np.float64(0.19245008972987523)),
 (315, np.float64(0.19245008972987523)),
 (412, np.float64(0.19245008972987523)),
 (467, np.float64(0.19245008972987523)),
 (535, np.float64(0.19245008972987523)),
 (746, np.float64(0.19245008972987523)),
 (773, np.float64(0.19245008972987523)),
 (1094, np.float64(0.19245008972987523)),
 (1273, np.float64(0.19245008972987523)),
 (1278, np.float64(0.19245008972987523)),
 (1304, np.float64(0.19245008972987523)),
 (1327, np.float64(0.19245008972987523)),
 (1440, np.float64(0.19245008972987523)),
 (1894, np.float64(0.19245008972987523)),
 (2131, np.float64(0.19245008972987523)),
 (2579, np.float64(0.19245008972987523)),
 (3554, np.float64(0.19245008972987523)),
 (3814, np.float64(0.19245008972987523)),
 (14, np.float64(0.18670401120373464)),
 (31, np.float64(0.18670401120373464)),
 (52, np.float64(0.18670401120373464)),
 (232, np.float64(0.18670401120373464)),
 (300, np.float64(0.18670401120373464)),
 (799, np.float64(0.18670401120373464)),
 (1297, np.float64(0.18670401120373464)),
 (97, np.float64(0.18257418583505539)),
 (304, np.float64(0.18257418583505539)),
 (368, np.float64(0.18257418583505539)),
 (486, np.float64(0.18257418583505539)),
 (543, np.float64(0.18257418583505539)),
 (791, np.float64(0.18257418583505539)),
 (1000, np.float64(0.18257418583505539)),
 (1002, np.float64(0.18257418583505539)),
 (1342, np.float64(0.18257418583505539)),
 (1520, np.float64(0.18257418583505539)),
 (1916, np.float64(0.18257418583505539)),
 (1941, np.float64(0.18257418583505539)),
 (2163, np.float64(0.18257418583505539)),
 (2319, np.float64(0.18257418583505539)),
 (2697, np.float64(0.18257418583505539)),
 (4348, np.float64(0.18257418583505539)),
 (26, np.float64(0.1814436846506058)),
 (46, np.float64(0.1814436846506058)),
 (127, np.float64(0.1814436846506058)),
 (129, np.float64(0.1814436846506058)),
 (207, np.float64(0.1814436846506058)),
 (266, np.float64(0.1814436846506058)),
 (342, np.float64(0.1814436846506058)),
 (778, np.float64(0.1814436846506058)),
 (870, np.float64(0.1814436846506058)),
 (1533, np.float64(0.1814436846506058)),
 (2129, np.float64(0.1814436846506058)),
 (3536, np.float64(0.1814436846506058)),
 (19, np.float64(0.17660431427533915)),
 (166, np.float64(0.17660431427533915)),
 (587, np.float64(0.17660431427533915)),
 (973, np.float64(0.17660431427533915)),
 (1992, np.float64(0.17660431427533915)),
 (18, np.float64(0.17407765595569785)),
 (56, np.float64(0.17407765595569785)),
 (67, np.float64(0.17407765595569785)),
 (86, np.float64(0.17407765595569785)),
 (121, np.float64(0.17407765595569785)),
 (157, np.float64(0.17407765595569785)),
 (241, np.float64(0.17407765595569785)),
 (294, np.float64(0.17407765595569785)),
 (362, np.float64(0.17407765595569785)),
 (379, np.float64(0.17407765595569785)),
 (472, np.float64(0.17407765595569785)),
 (505, np.float64(0.17407765595569785)),
 (581, np.float64(0.17407765595569785)),
 (627, np.float64(0.17407765595569785)),
 (814, np.float64(0.17407765595569785)),
 (920, np.float64(0.17407765595569785)),
 (1493, np.float64(0.17407765595569785)),
 (1804, np.float64(0.17407765595569785)),
 (1824, np.float64(0.17407765595569785)),
 (1920, np.float64(0.17407765595569785)),
 (1938, np.float64(0.17407765595569785)),
 (1975, np.float64(0.17407765595569785)),
 (2392, np.float64(0.17407765595569785)),
 (2492, np.float64(0.17407765595569785)),
 (2558, np.float64(0.17407765595569785)),
 (2864, np.float64(0.17407765595569785)),
 (2869, np.float64(0.17407765595569785)),
 (2997, np.float64(0.17407765595569785)),
 (3374, np.float64(0.17407765595569785)),
 (3618, np.float64(0.17407765595569785)),
 (158, np.float64(0.17213259316477408)),
 (160, np.float64(0.17213259316477408)),
 (169, np.float64(0.17213259316477408)),
 (740, np.float64(0.17213259316477408)),
 (1084, np.float64(0.17213259316477408)),
 (1476, np.float64(0.17213259316477408)),
 (2852, np.float64(0.17213259316477408)),
 (3216, np.float64(0.17213259316477408)),
 (3320, np.float64(0.17213259316477408)),
 (3352, np.float64(0.17213259316477408)),
 (3439, np.float64(0.17213259316477408)),
 (3744, np.float64(0.17213259316477408)),
 (3760, np.float64(0.17213259316477408)),
 (3908, np.float64(0.17213259316477408)),
 (3933, np.float64(0.17213259316477408)),
 (4008, np.float64(0.17213259316477408)),
 (4453, np.float64(0.17213259316477408)),
 (4502, np.float64(0.17213259316477408)),
 (150, np.float64(0.16798421022632323)),
 (813, np.float64(0.16798421022632323)),
 (1013, np.float64(0.16798421022632323)),
 (132, np.float64(0.16666666666666669)),
 (208, np.float64(0.16666666666666669)),
 (224, np.float64(0.16666666666666669)),
 (307, np.float64(0.16666666666666669)),
 (389, np.float64(0.16666666666666669)),
 (400, np.float64(0.16666666666666669)),
 (487, np.float64(0.16666666666666669)),
 (511, np.float64(0.16666666666666669)),
 (541, np.float64(0.16666666666666669)),
 (624, np.float64(0.16666666666666669)),
 (836, np.float64(0.16666666666666669)),
 (1029, np.float64(0.16666666666666669)),
 (1320, np.float64(0.16666666666666669)),
 (1323, np.float64(0.16666666666666669)),
 (1475, np.float64(0.16666666666666669)),
 (1874, np.float64(0.16666666666666669)),
 (2048, np.float64(0.16666666666666669)),
 (3325, np.float64(0.16666666666666669)),
 (55, np.float64(0.16412198797244362)),
 (491, np.float64(0.16412198797244362)),
 (501, np.float64(0.16412198797244362)),
 (654, np.float64(0.16412198797244362)),
 (1080, np.float64(0.16412198797244362)),
 (28, np.float64(0.16051447078102563)),
 (618, np.float64(0.16051447078102563)),
 (1069, np.float64(0.16051447078102563)),
 (1292, np.float64(0.16051447078102563)),
 (9, np.float64(0.16012815380508716)),
 (38, np.float64(0.16012815380508716)),
 (59, np.float64(0.16012815380508716)),
 (70, np.float64(0.16012815380508716)),
 (203, np.float64(0.16012815380508716)),
 (220, np.float64(0.16012815380508716)),
 (229, np.float64(0.16012815380508716)),
 (292, np.float64(0.16012815380508716)),
 (295, np.float64(0.16012815380508716)),
 (483, np.float64(0.16012815380508716)),
 (607, np.float64(0.16012815380508716)),
 (643, np.float64(0.16012815380508716)),
 (660, np.float64(0.16012815380508716)),
 (732, np.float64(0.16012815380508716)),
 (898, np.float64(0.16012815380508716)),
 (935, np.float64(0.16012815380508716)),
 (1140, np.float64(0.16012815380508716)),
 (1176, np.float64(0.16012815380508716)),
 (1200, np.float64(0.16012815380508716)),
 (1267, np.float64(0.16012815380508716)),
 (1497, np.float64(0.16012815380508716)),
 (1717, np.float64(0.16012815380508716)),
 (1829, np.float64(0.16012815380508716)),
 (1879, np.float64(0.16012815380508716)),
 (2001, np.float64(0.16012815380508716)),
 (2068, np.float64(0.16012815380508716)),
 (2816, np.float64(0.16012815380508716)),
 (149, np.float64(0.15713484026367724)),
 (381, np.float64(0.15713484026367724)),
 (518, np.float64(0.15713484026367724)),
 (610, np.float64(0.15713484026367724)),
 (678, np.float64(0.15713484026367724)),
 (960, np.float64(0.15713484026367724)),
 (1274, np.float64(0.15713484026367724)),
 (1307, np.float64(0.15713484026367724)),
 (1310, np.float64(0.15713484026367724)),
 (1449, np.float64(0.15713484026367724)),
 (1630, np.float64(0.15713484026367724)),
 (2124, np.float64(0.15713484026367724)),
 (2354, np.float64(0.15713484026367724)),
 (2616, np.float64(0.15713484026367724)),
 (2974, np.float64(0.15713484026367724)),
 (3186, np.float64(0.15713484026367724)),
 (3331, np.float64(0.15713484026367724)),
 (3426, np.float64(0.15713484026367724)),
 (3779, np.float64(0.15713484026367724)),
 (4095, np.float64(0.15713484026367724)),
 (4132, np.float64(0.15713484026367724)),
 (4158, np.float64(0.15713484026367724)),
 (4319, np.float64(0.15713484026367724)),
 (4339, np.float64(0.15713484026367724)),
 (4431, np.float64(0.15713484026367724)),
 (4654, np.float64(0.15713484026367724)),
 (33, np.float64(0.15430334996209194)),
 (39, np.float64(0.15430334996209194)),
 (79, np.float64(0.15430334996209194)),
 (101, np.float64(0.15430334996209194)),
 (233, np.float64(0.15430334996209194)),
 (249, np.float64(0.15430334996209194)),
 (311, np.float64(0.15430334996209194)),
 (332, np.float64(0.15430334996209194)),
 (373, np.float64(0.15430334996209194)),
 (413, np.float64(0.15430334996209194)),
 (589, np.float64(0.15430334996209194)),
 (612, np.float64(0.15430334996209194)),
 (728, np.float64(0.15430334996209194)),
 (977, np.float64(0.15430334996209194)),
 (978, np.float64(0.15430334996209194)),
 (1111, np.float64(0.15430334996209194)),
 (1156, np.float64(0.15430334996209194)),
 (1199, np.float64(0.15430334996209194)),
 (1688, np.float64(0.15430334996209194)),
 (2177, np.float64(0.15430334996209194)),
 (2345, np.float64(0.15430334996209194)),
 (2517, np.float64(0.15430334996209194)),
 (3626, np.float64(0.15430334996209194)),
 (3905, np.float64(0.15430334996209194)),
 (4468, np.float64(0.15430334996209194)),
 (190, np.float64(0.1543033499620919)),
 (1723, np.float64(0.1543033499620919)),
 (1435, np.float64(0.15396007178390023)),
 (27, np.float64(0.14907119849998599)),
 (37, np.float64(0.14907119849998599)),
 (138, np.float64(0.14907119849998599)),
 (426, np.float64(0.14907119849998599)),
 (665, np.float64(0.14907119849998599)),
 (781, np.float64(0.14907119849998599)),
 (922, np.float64(0.14907119849998599)),
 (1401, np.float64(0.14907119849998599)),
 (1492, np.float64(0.14907119849998599)),
 (1752, np.float64(0.14907119849998599)),
 (1955, np.float64(0.14907119849998599)),
 (302, np.float64(0.14547859349066158)),
 (479, np.float64(0.14547859349066158)),
 (600, np.float64(0.14547859349066158)),
 (776, np.float64(0.14547859349066158)),
 (1247, np.float64(0.14547859349066158)),
 (1290, np.float64(0.14547859349066158)),
 (1299, np.float64(0.14547859349066158)),
 (1603, np.float64(0.14547859349066158)),
 (1978, np.float64(0.14547859349066158)),
 (2108, np.float64(0.14547859349066158)),
 (2116, np.float64(0.14547859349066158)),
 (2246, np.float64(0.14547859349066158)),
 (2391, np.float64(0.14547859349066158)),
 (2508, np.float64(0.14547859349066158)),
 (2655, np.float64(0.14547859349066158)),
 (3609, np.float64(0.14547859349066158)),
 (3719, np.float64(0.14547859349066158)),
 (3820, np.float64(0.14547859349066158)),
 (3830, np.float64(0.14547859349066158)),
 (3858, np.float64(0.14547859349066158)),
 (3924, np.float64(0.14547859349066158)),
 (3992, np.float64(0.14547859349066158)),
 (4088, np.float64(0.14547859349066158)),
 (4163, np.float64(0.14547859349066158)),
 (4179, np.float64(0.14547859349066158)),
 (4329, np.float64(0.14547859349066158)),
 (4353, np.float64(0.14547859349066158)),
 (4516, np.float64(0.14547859349066158)),
 (4602, np.float64(0.14547859349066158)),
 (4624, np.float64(0.14547859349066158)),
 (4626, np.float64(0.14547859349066158)),
 (35, np.float64(0.14433756729740643)),
 (68, np.float64(0.14433756729740643)),
 (122, np.float64(0.14433756729740643)),
 (230, np.float64(0.14433756729740643)),
 (242, np.float64(0.14433756729740643)),
 (369, np.float64(0.14433756729740643)),
 (420, np.float64(0.14433756729740643)),
 (508, np.float64(0.14433756729740643)),
 (768, np.float64(0.14433756729740643)),
 (1508, np.float64(0.14433756729740643)),
 (2968, np.float64(0.14433756729740643)),
 (3307, np.float64(0.14433756729740643)),
 (3468, np.float64(0.14433756729740643)),
 (16, np.float64(0.140028008402801)),
 (20, np.float64(0.140028008402801)),
 (30, np.float64(0.140028008402801)),
 (63, np.float64(0.140028008402801)),
 (88, np.float64(0.140028008402801)),
 (96, np.float64(0.140028008402801)),
 (107, np.float64(0.140028008402801)),
 (279, np.float64(0.140028008402801)),
 (403, np.float64(0.140028008402801)),
 (503, np.float64(0.140028008402801)),
 (547, np.float64(0.140028008402801)),
 (1017, np.float64(0.140028008402801)),
 (1154, np.float64(0.140028008402801)),
 (1295, np.float64(0.140028008402801)),
 (1379, np.float64(0.140028008402801)),
 (1619, np.float64(0.140028008402801)),
 (2914, np.float64(0.140028008402801)),
 (3620, np.float64(0.140028008402801)),
 (183, np.float64(0.1382602259640567)),
 (3145, np.float64(0.1382602259640567)),
 (112, np.float64(0.13608276348795437)),
 (151, np.float64(0.13608276348795437)),
 (174, np.float64(0.13608276348795437)),
 (271, np.float64(0.13608276348795437)),
 (275, np.float64(0.13608276348795437)),
 (419, np.float64(0.13608276348795437)),
 (579, np.float64(0.13608276348795437)),
 (591, np.float64(0.13608276348795437)),
 (900, np.float64(0.13608276348795437)),
 (1144, np.float64(0.13608276348795437)),
 (2782, np.float64(0.13608276348795437)),
 (2827, np.float64(0.13608276348795437)),
 (3441, np.float64(0.13608276348795437)),
 (3447, np.float64(0.13608276348795437)),
 (4077, np.float64(0.13608276348795437)),
 (4673, np.float64(0.13608276348795437)),
 (48, np.float64(0.13608276348795434)),
 (125, np.float64(0.13608276348795434)),
 (309, np.float64(0.13608276348795434)),
 (461, np.float64(0.13608276348795434)),
 (668, np.float64(0.13608276348795434)),
 (831, np.float64(0.13608276348795434)),
 (990, np.float64(0.13608276348795434)),
 (1003, np.float64(0.13608276348795434)),
 (1075, np.float64(0.13608276348795434)),
 (1260, np.float64(0.13608276348795434)),
 (1271, np.float64(0.13608276348795434)),
 (1455, np.float64(0.13608276348795434)),
 (1601, np.float64(0.13608276348795434)),
 (1610, np.float64(0.13608276348795434)),
 (1711, np.float64(0.13608276348795434)),
 (1737, np.float64(0.13608276348795434)),
 (1743, np.float64(0.13608276348795434)),
 (1880, np.float64(0.13608276348795434)),
 (2049, np.float64(0.13608276348795434)),
 (2066, np.float64(0.13608276348795434)),
 (2247, np.float64(0.13608276348795434)),
 (2322, np.float64(0.13608276348795434)),
 (2484, np.float64(0.13608276348795434)),
 (2646, np.float64(0.13608276348795434)),
 (2807, np.float64(0.13608276348795434)),
 (2901, np.float64(0.13608276348795434)),
 (2902, np.float64(0.13608276348795434)),
 (2988, np.float64(0.13608276348795434)),
 (3023, np.float64(0.13608276348795434)),
 (3053, np.float64(0.13608276348795434)),
 (3089, np.float64(0.13608276348795434)),
 (3100, np.float64(0.13608276348795434)),
 (3135, np.float64(0.13608276348795434)),
 (3138, np.float64(0.13608276348795434)),
 (3230, np.float64(0.13608276348795434)),
 (3321, np.float64(0.13608276348795434)),
 (3375, np.float64(0.13608276348795434)),
 (3398, np.float64(0.13608276348795434)),
 (3404, np.float64(0.13608276348795434)),
 (3524, np.float64(0.13608276348795434)),
 (3653, np.float64(0.13608276348795434)),
 (3689, np.float64(0.13608276348795434)),
 (3706, np.float64(0.13608276348795434)),
 (3947, np.float64(0.13608276348795434)),
 (4060, np.float64(0.13608276348795434)),
 (4129, np.float64(0.13608276348795434)),
 (4133, np.float64(0.13608276348795434)),
 (4149, np.float64(0.13608276348795434)),
 (4164, np.float64(0.13608276348795434)),
 (4403, np.float64(0.13608276348795434)),
 (4420, np.float64(0.13608276348795434)),
 (4434, np.float64(0.13608276348795434)),
 (4469, np.float64(0.13608276348795434)),

In [67]:
# To get top 5 similar movies
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(47, np.float64(0.3849001794597506)),
 (2374, np.float64(0.34426518632954817)),
 (61, np.float64(0.3333333333333334)),
 (83, np.float64(0.3142696805273545)),
 (2405, np.float64(0.30123203803835463))]

In [68]:
# Get index of movie by movie name
df[df['title'] == 'John Carter'].index[0]

np.int64(4)

In [69]:
df.iloc[1349].title

'Aloha'

In [70]:
# Creating a function to recommand top 5 movies related to search

def recommand(movie):
    idx = df[df['title'] == movie].index[0]
    dist = similarity[idx]
    movie_list = sorted(list(enumerate(dist)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(df.iloc[i[0]].title)

In [71]:
recommand('Batman Begins')

The Dark Knight
The Dark Knight Rises
Amidst the Devil's Wings
Mi America
Ajami

In [72]:
recommand('John Carter')

Stargate: The Ark of Truth
Six-String Samurai
Predator
Megaforce
Earth to Echo

In [73]:
import pickle

In [75]:
pickle.dump(df,open('movies.pkl','wb'))

In [74]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [74]:
pickle.dump(df.to_dict(),open('movies_dict.pkl','wb'))